### ISSUE TITLE
Automation variable et «rythmée» dans 222

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC2#12]
Je me suis demandé si la résolution de l'écriture de l'automation avait à voir avec la qualité de la reproduction des figures créées par les trajectoires.
Setup:
DP; Jack; Zirkonium
Mavericks
ZirkOSC2 2.2.2.
Spiral 20s 2cycle(s)
Fichier audio octophonique

Écriture de l'automation une piste à la fois, 6 pistes ici en comparaison, avec 6 résolutions différentes (les valeurs de réglages sont indiquées dans le nom de la piste), de la plus dense à la plus légère.
On voit que les formes dessinées sont toujours les mêmes.
![dp six resolutions zoom out](https://cloud.githubusercontent.com/assets/8959779/8356182/202db4d4-1b54-11e5-9301-f1e975186cc7.jpg)

Ce qu'on voit cependant lorsqu'on effectue un Zoom in c'est que la quantité de points est de moins en moins dense, mais ils ne contribuent pas à dessiner une forme plus précise.
Par contre on peut clairement constater que les discontinuités dans l'écriture (les lignes plates) sont toujours au même moment, quelle que soit la résolution de l'automation!
Comme si une pulsation régulière contrôlait l'écriture de l'automation:
![dp six resolutions zoom in](https://cloud.githubusercontent.com/assets/8959779/8356200/368e0f3a-1b54-11e5-81b1-c73e7e92fc97.jpg)

D'ailleurs, j'ai déjà décrit le fait qu'on entendait cette pulsation au moment de l'écriture.
Et bien avec cette version 2.2.2, on ne l'entend plus!
Et dans DP, il y a deux moniteurs de CPU: un pour le CPU lui-même et un pour le playback. Ce dernier pulsait lorsque de l'écriture de l'automation auparavant.
Mais là, il ne le fait plus...
![dp processing playback](https://cloud.githubusercontent.com/assets/8959779/8356227/635b96c2-1b54-11e5-93b0-fedf1e6671e4.jpg)

Et apparemment tes tests se font aussi sans audio!!!
C'est bien, comme cela on pourrait diffuser du silence dans aucun hp!
C'est très Cagien comme concept!
Malheureusement avec de l'audio et en situation réelle avec le Zirkonium, ce n'est pas aussi joli.
La piste du dessus utilise la fonction Sample Accurate.
Avec la deuxième j'ai ajouté l'option Low Latency.
Pas un grand succès.
Donc si je résume, le problème est essentiellement avec Logic, non!

![logic zirkosc 222](https://cloud.githubusercontent.com/assets/8959779/8356264/90ae3db4-1b54-11e5-9a8b-fe052be50dbb.jpg)

And tze winneur is: Reaper!
Excepté que la version VST 222 n'est pas reconnue par Reaper.
Le test a été fait avec la version AU.
La VST, bien qu'elle passe le test de validation dans DP, n'est pas non plus utilisable par lui.
![reaper au 222xy](https://cloud.githubusercontent.com/assets/8959779/8356286/aca03af4-1b54-11e5-81fe-7d569559e22a.jpg)

**Comment by DominicThibault** [comment]
J'ai fait quelques tests aujourd'hui (dans DP) pour essayer d'identifier la source de cette latence périodique dans l'écriture des automations. Je n'ai rien découvert de très concluant mais je mettrai quand même mon travail ici pour qu'on ne refasse pas les mêmes tests.

1) Avec et sans les communications OSC vers le Zirkonium:

Ici, avec les communications OSC entrantes et sortantes:
![zirkosc_2_2_2_osc_withreturn](https://cloud.githubusercontent.com/assets/8837086/8412361/6626707e-1e57-11e5-8c9a-e9d72d9b0f2d.jpg)

Ici, sans la communication entrante OSC:
![zirkosc_2_2_2_osc_withoutreturn](https://cloud.githubusercontent.com/assets/8837086/8412368/6ef3d76e-1e57-11e5-9cb2-d36315387caa.jpg)

ici, sans les communications entrantes et sortantes:
![zirkosc_2_2_2_osc_withoutsend](https://cloud.githubusercontent.com/assets/8837086/8412393/a3bc0c1e-1e57-11e5-8f64-dade8db1314e.jpg)

Et ici avec le communication OSC ("OSC active") décochée
![zirkosc_2_2_2_osc_inactive](https://cloud.githubusercontent.com/assets/8837086/8412416/cab5aa50-1e57-11e5-9e5e-f15c34fbbc96.jpg)

Comme vous voyez, ça ne change pas grand chose à la qualité d'écriture.

**Comment by DominicThibault** [comment]
Alors, je me suis dit que c'était p-e le niveau de priorité du thread de DP. 
![zirkosc_2_2_2_workpriority_window](https://cloud.githubusercontent.com/assets/8837086/8412794/4608f8d6-1e5a-11e5-938c-2523a8e57df2.jpg)

J'ai essayé les 3 modes (High, medium, low) et ça n'a rien changé.

**Comment by DominicThibault** [comment]
Alors, j'ai essayé de voir si la "latency compensation" pouvait avoir un impact:

activée:
![zirkosc_2_2_2_latencycompensation_on](https://cloud.githubusercontent.com/assets/8837086/8412912/f6408aa2-1e5a-11e5-9a1d-5e5577f45a5e.jpg)

éteinte:
![zirkosc_2_2_2_latencycompensation_off](https://cloud.githubusercontent.com/assets/8837086/8412922/ffcf531e-1e5a-11e5-9e5c-bd0055a5909b.jpg)

Sans trop de succès.

**Comment by Normandeau** [comment]
Merci Dominic.
C'est ça le beta testing.
Passer des heures à tester et à ne rien trouver!
Mais au moins on sait que ce n'est pas cela!
Ce n'est pas rien, bien au contraire.

Le 2015-06-29 à 18:11, Dominic Thibault <notifications@github.com> a écrit :

> J'ai fait quelques tests aujourd'hui (dans DP) pour essayer d'identifier la source de cette latence périodique dans l'écriture des automations. Je n'ai rien découvert de très concluant mais je mettrai quand même mon travail ici pour qu'on ne refasse pas les mêmes tests.
> 
> 1) Avec et sans les communications OSC vers le Zirkonium:
> 
> Ici, avec les communications OSC entrantes et sortantes:
> 
> 
> Ici, sans la communication entrante OSC:
> 
> 
> ici, sans les communications entrantes et sortantes:
> 
> 
> Et ici avec le communication OSC ("OSC active") décochée
> 
> 
> Comme vous voyez, ça ne change pas grand chose à la qualité d'écriture.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Bonne journée

•••••••••••••••••••••••••••••••••••••••
Robert Normandeau
Vice-doyen aux études en création et technologie
Professeur titulaire de composition électroacoustique
Faculté de musique, B-660, 343-6111 poste 3486
Université de Montréal
http://www.musique.umontreal.ca/personnel/normandeau_r.html

**Comment by vberthiaume** [comment]
Oui, comme dit Robert, merci Dominic, c'est super utile!

V

2015-06-29 12:38 GMT-04:00 Robert Normandeau <notifications@github.com>:

**Comment by vberthiaume** [comment]
autres tests dans #13
